[[constraint]]
  name = "k8s.io/kubernetes"
  version = "=v1.14.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.14.2"

[[override]]
  name = "github.com/docker/docker"
  version = "v1.12.6"
